### ISSUE TITLE
Transform, Streams, and Finished

### ISSUE THREAD

**Issue by devourment77** [wdavidw/node-csv#201] opened 2015-07-11 18:09 UTC
Hello,

When using node-csv parse and transform in a stream (asynchronous with parallel: 25), it seems the stream "finish" event is triggering when the csv read is complete, and not when the last transform callback was invoked.  I tried using the parse and transform finish events as well, but they completed even before the stream finish event.

Is it possible to know when the last transform callback has completed?

```
// really large csv
var csvFile = './uploads/someFile.tab';

// csv-parser options, see http://csv.adaltas.com/parse/
var parser = csv.parse({
    delimiter: '\t',
    columns: true,
    skip_empty_lines: true,
    trim: true,
    relax: true
});

// catch any csv parse errors
parser.on('error', function(err) {
    return logger.error(err);
});

// setup transformer to process each row. This could be done in parse, BUT we want to use the parallel feature
// of transform to restrict how many rows are being read at a time
var transformer = csv.transform(function(row, callback) {
    // do some work here
    callback(null, row);
}, {
    parallel: 25
});

// catch any csv transform errors
transformer.on('error', function(err) {
    return logger.error(err);
});

// create read stream and pipe
var stream = fs.createReadStream(csvFile).pipe(parser).pipe(transformer);

// stream complete event, let async waterfall know we're done, BUT it seems our callbacks are not finished yet :(
stream.on('finish', function() {
    logger.info('finshed reading from csv file stream');

    return waterfallCallback(null, {
        source: source
    });
});
```

**Comment by wdavidw** [comment] 2015-07-14 06:55
can u share the csv file?

**Comment by devourment77** [comment] 2015-07-24 17:09
It is really large (around 2 gb).  Everything seems to be parsing fine, just the finish event is being triggered before my callbacks return on my transformer (specifically saving the record to mongo).

**Comment by seifertd** [comment] 2015-08-04 00:49
Here is a gist exhibiting the problem:

https://gist.github.com/seifertd/6403ad9c357d7b1fd3e5

Is there an event the transformer will generate when it is done? Since it is a Stream, perhaps it gets a finished event too?

**Comment by seifertd** [comment] 2015-08-04 01:00
The transformer does emit a 'finished' event, but the code in my gist is flawed. It must wait for all inserts to complete before returning. 

I updated the gist with a new version that does that.

OP, perhaps you are seeing some variation of this?

**Comment by wdavidw** [comment] 2015-08-04 12:26
you're code shall really help if it reproduce the probleme. i'll try to find some time (probably next week) to download and test this.

**Comment by devourment77** [comment] 2015-08-04 12:32
@seifertd I think they probably are similar issues.  For me, I was getting a transform "finish" event, it was just firing before all my transform callbacks were complete (instead it was firing when the csv was finished parsing).

**Comment by edwin177** [comment] 2015-11-25 08:15
I see the same issue of the 'finish' event triggering before the async transforms are done.

@seifertd were you able to resolve this?

**Comment by rntorm** [comment] 2016-06-22 10:40
@seifertd @wdavidw Any known solution to this? As far as I've messed around with parallel processing on transformer, it seems that for some reason the 'finish' event is called just before the last patch of transforming is initiated

My findings are based on the snippet below. I had 3921 lines in the CSV files and `output.length` is always `3500`:

https://gist.github.com/rntorm/6a048914e03e249051da3ea6e7733c5c

**Comment by rntorm** [comment] 2016-06-22 12:10
Got it working by using on 'end' event instead of 'finish'

**Comment by wdavidw** [comment] 2016-06-22 18:33
which make sense, you are consuming a stream, meaning you are connected to a stream reader, so you must listen to a [stream reader event](https://nodejs.org/dist/latest-v6.x/docs/api/stream.html#stream_readable_streams).

**Comment by wdavidw** [comment] 2016-06-22 18:33
could we close this issue?

**Comment by devourment77** [comment] 2016-07-14 17:59
I know this is old, but I ended up resolving it following your advice here: https://github.com/wdavidw/node-stream-transform/issues/17

- { consume: true } is set as a transform option
- .on("end" ... ) is used on the transform object

**Comment by wdavidw** [comment] 2016-07-17 19:41
thanks

**Closed by wdavidw** 2016-07-17 19:41 UTC
